source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

gem 'spring', :group => :development

gem 'haml-rails'

gem 'listen', '~> 3.1.5'

# gem 'sqlite3'
gem 'mysql2'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
gem 'byebug'
gem 'pry-byebug'
gem 'rb-readline'

gem 'bcrypt'
gem 'responders'
